In [ ]:
""" import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)
Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables."""

Ans:
    Yes,there is a differences in the data type of variables list_ and array_list..

In [1]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)
list_

['1', '2', '3', '4', '5']

In [2]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [3]:
print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


In [4]:
""" Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list. """
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
for i in list_:
    print(type(i))


<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [6]:
import numpy as np
array_list = np.array(object = list_)
for i in array_list:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [ ]:
""" Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list."""
Ans:
    Yes,there is a difference in the data type of the elements present in both the variables,list_ and arra_list

In [10]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [11]:
array_list = np.array(object = list_, dtype = int)
for i in array_list:
    print(type(i))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [13]:
"Consider the below code to answer further questions:"
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
print(num_list)
print(num_array)

[[1, 2, 3], [4, 5, 6]]
[[1 2 3]
 [4 5 6]]


In [14]:
"""Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size """
import numpy as np
num_array = np.array(object = num_list)
print(np.shape(num_array))

(2, 3)


In [15]:
print(np.size(num_array))

6


In [20]:
""" Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).] """
#code:
import numpy.matlib as nm
data = nm.zeros((3,3))
data

matrix([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [21]:
nm.size(data)

9

In [22]:
nm.shape(data)

(3, 3)

In [29]:
""" Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.] """
#code:
import numpy.matlib as nm
data = nm.eye(5)
data

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [30]:
nm.shape(data)

(5, 5)